-- 1. User Directory Data Node
CREATE TABLE IF NOT EXISTS chat_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mobile_number TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    registered_at TEXT NOT NULL
);

-- 2. Transmission Logs Message Tracker
CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_num TEXT NOT NULL,
    receiver_num TEXT NOT NULL,
    message_text TEXT DEFAULT '',
    media_url TEXT DEFAULT 'None',
    media_type TEXT DEFAULT 'None', -- text, photo, video
    timestamp TEXT NOT NULL,
    is_seen BOOLEAN DEFAULT FALSE
);

